name: Deploy Jekyll Blog

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Use the version required by your project
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build --destination _site

    - name: Copy to shared directory
      run: |
        cp -r _site/* /blog/_site/

